# Detectron2 hyperparameters
Detectron2:
    EVAL_PERIOD : 5000 
    DATALOADER_NUM_WORKERS : 8
    SOLVER_IMS_PER_BATCH : 4
    SOLVER_BASE_LR : 0.001 
    SOLVER_CHECKPOINT_PERIOD : 5000 
    SOLVER_MAX_ITER : 40000  
    SOLVER_STEPS: [20000, 30000]
    DATALOADER_SAMPLER_TRAIN: 'RepeatFactorTrainingSampler'
    SOLVER_LR_SCHEDULER_NAME: 'WarmupMultiStepLR'
    MODEL_ROI_HEADS_BATCH_SIZE_PER_IMAGE : 512
    LABEL_LIST : 
        Deepfashion: ['short sleeve top',
                 'long sleeve top',
                 'short sleeve outwear',
                 'long sleeve outwear',
                 'vest',
                 'sling',
                 'shorts',
                 'trousers',
                 'skirt',
                 'short sleeve dress',
                 'long sleeve dress',
                 'vest dress',
                 'sling dress']
                 
        kfashion : ['cardigan',
                     'knitwear',
                     'dress',
                     'leggings',
                     'vest',
                     'bratop',
                     'blouse',
                     'shirts',
                     'skirt',
                     'jacket',
                     'jumper',
                     'jumpsuit',
                     'jogger pants',
                     'zipup',
                     'jean',
                     'coat',
                     'top',
                     't-shirts',
                     'padded jacket',
                     'pants',
                     'hoody']

cgd:
    SOLVER_IMS_PER_BATCH : 20
    EVAL_PERIOD: 10000
    MAX_ITERS: 100000
    LR : 0.001
    FEATURE_DIM : 768
    BASE_DIM: 256
    GD_CONFIG : [1,2,3]
    NUM_CLASS : 8509
    TEMP_SCALE : 0.5
    SMOOTHING : 0.1
    TRIPLE_MARGIN : 0.1
    

reg:
    CATE_MASTER_DICT: {'upper': ['jacket', 'padded jacket', 'coat', 'jumper', 'cardigan',
                                 't-shirts', 'top', 'jumpsuit', 'hoody', 'blouse', 'knitwear',
                                 'shirts', 'vest'],
                       'lower': ['pants', 'jean', 'leggings', 'skirt', 'jogger pants'],
                       'block': ['dress']}
                       
exception:
    seg:
        check_image: 'FAIL-001'
        check_num_labels: 'FAIL-002'
    reg:
        'base_extract': 'FAIL_001',
        'check_not_block': 'FAIL_002'
